apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cartservice-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: cartservice
  duration: "60s"
  scheduler:
    cron: "@every 10m"

