[k8s_nodes]
worker-node-1 ansible_host=10.0.1.10 ansible_user=cloud-admin
worker-node-2 ansible_host=10.0.1.11 ansible_user=cloud-admin

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

